# Generated by Django 4.2 on 2025-01-10 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credit_management", "0002_seller_credit_alter_chargerequest_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
