# Generated by Django 4.2 on 2025-01-10 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("credit_management", "0003_seller_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Your phone number must start with 09 and be entered with English digits.",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "text",
                    models.CharField(max_length=100, verbose_name="Notification Title"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="credit_management.seller",
                        verbose_name="Seller",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
